version: '2'

services:
  local:
    build: ./server
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - localProxy
      - localTesting
      - localDatabase

  production:
    build: ./server
    volumes:
      - "./authorized_keys:/home/user/.ssh/authorized_keys"
      - "./server/testApp:/var/www/production"
      - "./server/testApp:/var/www/staging"
    networks:
      - proxyProduction
      - productionDatabase
      - stagingDatabase

  proxy:
    build: ./server
    volumes:
      - "./authorized_keys:/home/user/.ssh/authorized_keys"
    networks:
      - localProxy
      - testingProxy
      - proxyProduction

  testing:
    build: ./server
    volumes:
      - "./authorized_keys:/home/user/.ssh/authorized_keys"
      - "./server/testApp:/var/www/testing"
    networks:
      - testingProxy
      - localTesting
      - testingDatabase

  local-db:
    build: ./database
    networks:
      - localDatabase
    environment:
      MYSQL_ROOT_PASSWORD: localPw
      MYSQL_DATABASE: sequelmovie
    volumes:
      - ./database/db-seed:/docker-entrypoint-initdb.d

  production-db:
    build: ./database
    networks:
      - productionDatabase
    environment:
      MYSQL_ROOT_PASSWORD: productionPw
      MYSQL_DATABASE: sequelmovie
    volumes:
      - ./database/db-seed:/docker-entrypoint-initdb.d

  staging-db:
    build: ./database
    networks:
      - stagingDatabase
    environment:
      MYSQL_ROOT_PASSWORD: stagingPw
      MYSQL_DATABASE: sequelmovie
    volumes:
      - ./database/db-seed:/docker-entrypoint-initdb.d

  testing-db:
    build: ./database
    networks:
      - testingDatabase
    environment:
      MYSQL_ROOT_PASSWORD: testingPw
      MYSQL_DATABASE: sequelmovie
    volumes:
      - ./database/db-seed:/docker-entrypoint-initdb.d

networks:
  localProxy:
    driver: bridge
  localTesting:
    driver: bridge
  proxyProduction:
    driver: bridge
  testingProxy:
    driver: bridge

  localDatabase:
    driver: bridge
  productionDatabase:
    driver: bridge
  stagingDatabase:
    driver: bridge
  testingDatabase:
    driver: bridge
