version: '2'

services:
  host_a:
    build: .
    volumes:
      - "./authorized_keys:/home/user/.ssh/authorized_keys"
    ports:
      - "2208:22"
    networks:
      - hostAB
  host_b:
    build: .
    volumes:
      - "./authorized_keys:/home/user/.ssh/authorized_keys"
    networks:
      - hostAB
      - hostBC
  host_c:
    build: .
    volumes:
      - "./authorized_keys:/home/user/.ssh/authorized_keys"
      - "./testApp:/var/www/prod"
      - "./testApp:/var/www/testing"
    networks:
      - hostBC
      - database
  database:
    image: mysql:5.7
    networks:
      - database
    ports:
      - "2206:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sequelmovie
    volumes:
      - ./db-seed:/docker-entrypoint-initdb.d

networks:
  hostAB:
    driver: bridge
  hostBC:
    driver: bridge
  database:
    driver: bridge
